import { Commitment, Course, Plan, PlannerState, Preferences } from "@/lib/types";

const sampleCourses: Course[] = [
  {
    id: "course-cs110",
    name: "CS 110 Applied Programming",
    meetingDays: ["Mon", "Wed"],
    startTime: "09:30",
    endTime: "10:45",
    workloadHours: 5,
    difficulty: "medium",
    requirement: "required",
    color: "bg-emerald-300/80 border-emerald-500/60 text-emerald-950",
    deadlines: [{ id: "cs110-project", title: "Portfolio check-in", date: "2026-05-02" }],
  },
  {
    id: "course-wr150",
    name: "WR 150 Writing Seminar",
    meetingDays: ["Tue", "Thu"],
    startTime: "14:00",
    endTime: "15:15",
    workloadHours: 4,
    difficulty: "medium",
    requirement: "required",
    color: "bg-sky-300/80 border-sky-500/60 text-sky-950",
    deadlines: [{ id: "wr150-essay", title: "Final essay", date: "2026-05-12" }],
  },
  {
    id: "course-ec101",
    name: "EC 101 Intro Economics",
    meetingDays: ["Mon", "Wed", "Fri"],
    startTime: "13:00",
    endTime: "13:50",
    workloadHours: 4,
    difficulty: "medium",
    requirement: "elective",
    color: "bg-amber-200/90 border-amber-500/60 text-amber-950",
    deadlines: [{ id: "ec101-exam", title: "Unit exam", date: "2026-05-18" }],
  },
  {
    id: "course-ph100",
    name: "PH 100 Intro Philosophy",
    meetingDays: ["Mon", "Wed"],
    startTime: "16:00",
    endTime: "17:15",
    workloadHours: 2,
    difficulty: "easy",
    requirement: "elective",
    color: "bg-rose-200/90 border-rose-500/60 text-rose-950",
    deadlines: [{ id: "ph100-paper", title: "Reflection paper", date: "2026-05-23" }],
  },
  {
    id: "course-cs210",
    name: "CS 210 Algorithms",
    meetingDays: ["Mon", "Wed"],
    startTime: "09:30",
    endTime: "10:45",
    workloadHours: 9,
    difficulty: "hard",
    requirement: "required",
    color: "bg-violet-200/90 border-violet-500/60 text-violet-950",
    deadlines: [{ id: "cs210-midterm", title: "Midterm", date: "2026-05-02" }],
  },
  {
    id: "course-ma225",
    name: "MA 225 Linear Algebra",
    meetingDays: ["Tue", "Thu"],
    startTime: "11:00",
    endTime: "12:15",
    workloadHours: 8,
    difficulty: "hard",
    requirement: "required",
    color: "bg-lime-200/90 border-lime-500/60 text-lime-950",
    deadlines: [{ id: "ma225-final", title: "Final exam", date: "2026-05-07" }],
  },
  {
    id: "course-bi140",
    name: "BI 140 Biology Lab",
    meetingDays: ["Tue"],
    startTime: "18:00",
    endTime: "20:45",
    workloadHours: 8,
    difficulty: "hard",
    requirement: "required",
    color: "bg-cyan-200/90 border-cyan-500/60 text-cyan-950",
    deadlines: [{ id: "bi140-practical", title: "Lab practical", date: "2026-05-14" }],
  },
  {
    id: "course-ds201",
    name: "DS 201 Data Systems",
    meetingDays: ["Tue", "Thu"],
    startTime: "09:00",
    endTime: "10:15",
    workloadHours: 9,
    difficulty: "hard",
    requirement: "required",
    color: "bg-fuchsia-200/90 border-fuchsia-500/60 text-fuchsia-950",
    deadlines: [{ id: "ds201-exam", title: "Architecture exam", date: "2026-05-06" }],
  },
  {
    id: "course-ch230",
    name: "CH 230 Organic Chemistry",
    meetingDays: ["Mon", "Wed"],
    startTime: "10:00",
    endTime: "10:50",
    workloadHours: 7,
    difficulty: "hard",
    requirement: "required",
    color: "bg-orange-200/90 border-orange-500/60 text-orange-950",
    deadlines: [{ id: "ch230-quiz", title: "Reaction mechanisms quiz", date: "2026-05-15" }],
  },
  {
    id: "course-ps230",
    name: "PS 230 Cognitive Psychology",
    meetingDays: ["Tue", "Thu"],
    startTime: "15:30",
    endTime: "16:45",
    workloadHours: 5,
    difficulty: "medium",
    requirement: "elective",
    color: "bg-indigo-200/90 border-indigo-500/60 text-indigo-950",
    deadlines: [{ id: "ps230-exam", title: "Memory systems exam", date: "2026-05-07" }],
  },
  {
    id: "course-ar110",
    name: "AR 110 Design Studio",
    meetingDays: ["Fri"],
    startTime: "09:00",
    endTime: "11:45",
    workloadHours: 5,
    difficulty: "medium",
    requirement: "elective",
    color: "bg-teal-200/90 border-teal-500/60 text-teal-950",
    deadlines: [{ id: "ar110-critique", title: "Studio critique", date: "2026-05-08" }],
  },
  {
    id: "course-com240",
    name: "COM 240 Media Studies",
    meetingDays: ["Mon", "Wed"],
    startTime: "12:00",
    endTime: "13:15",
    workloadHours: 4,
    difficulty: "medium",
    requirement: "elective",
    color: "bg-stone-200/90 border-stone-500/60 text-stone-950",
    deadlines: [{ id: "com240-presentation", title: "Campaign presentation", date: "2026-05-09" }],
  },
];

const sampleCommitments: Commitment[] = [
  {
    id: "commitment-job",
    title: "Campus Bookstore Shift",
    category: "job",
    meetingDays: ["Mon", "Wed", "Fri"],
    startTime: "17:30",
    endTime: "21:00",
    color: "bg-slate-200/95 border-slate-500/60 text-slate-900",
  },
  {
    id: "commitment-club",
    title: "Debate Club",
    category: "club",
    meetingDays: ["Tue"],
    startTime: "19:00",
    endTime: "20:30",
    color: "bg-orange-200/90 border-orange-500/60 text-orange-950",
  },
  {
    id: "commitment-exercise",
    title: "Gym / Recharge Block",
    category: "exercise",
    meetingDays: ["Tue", "Thu", "Sat"],
    startTime: "07:30",
    endTime: "08:30",
    color: "bg-teal-200/90 border-teal-500/60 text-teal-950",
  },
];

const samplePreferences: Preferences = {
  sleepStart: "23:30",
  sleepEnd: "07:30",
  maxStudyHoursPerDay: 5,
  maxClassesPerDay: 3,
};

const samplePlans: Plan[] = [
  {
    id: "planA",
    name: "Plan A",
    profileLabel: "Overloaded",
    description: "Six demanding courses, one direct class conflict, and an evening commitment collision make this the highest-risk path.",
    courseIds: [
      "course-cs210",
      "course-ma225",
      "course-wr150",
      "course-bi140",
      "course-ds201",
      "course-ch230",
    ],
  },
  {
    id: "planB",
    name: "Plan B",
    profileLabel: "Balanced",
    description: "Four courses with lighter weekly study demand, no hard conflicts, and deadlines spaced across the month.",
    courseIds: ["course-cs110", "course-wr150", "course-ec101", "course-ph100"],
  },
  {
    id: "planC",
    name: "Plan C",
    profileLabel: "Deadline-heavy",
    description: "The timetable is manageable, but four major assessments land inside the same four-day stretch.",
    courseIds: ["course-ds201", "course-ps230", "course-ar110", "course-com240"],
  },
];

export const samplePlannerState: PlannerState = {
  courses: sampleCourses,
  commitments: sampleCommitments,
  preferences: samplePreferences,
  plans: samplePlans,
  activePlanId: "planA",
};
